/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "panoply.h"

int *
register_1_svc(member_t *argp, struct svc_req *rqstp)
{
	static int  result;

	if(members_list.last_inserted == 0) {
		argp->id = 0;
		argp->type = 0;
	}
	members_list.data[members_list.last_inserted] = *argp;
	members_list.last_inserted += 1;

	result = 0;
	return &result;
}

int *
login_1_svc(member_t *argp, struct svc_req *rqstp)
{
	static int  result = -1;

	/*
	 * On vérifie que l'utililsateur existe dans la liste des membres.
	 */
	 int found = 0, index = 0, valid_username = -1, valid_password = -1;
	 while(found == 0 && index < members_list.last_inserted) {
		 	valid_username = strcpy(members_list.data[index].user_name, argp->user_name);
			valid_password = strcpy(members_list.data[index].password, argp->password);

			if(valid_username == 0 && valid_password == 0)
				found = 1;
			else
				index++;
	 }

	 // Si l'utilisateur est trouvé, on retourne son identifiant.
	 if(found == 1) result = members_list.data[index].id;

	return &result;
}

int *
total_members_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;
	result = members_list.last_inserted;
	return &result;
}

member_t *
show_member_1_svc(int *argp, struct svc_req *rqstp)
{
	static member_t  result;

	int found = 0, index = 0;
	while(found == 0 && index < members_list.last_inserted) {
		if(members_list.data[index].id == *argp)
			found = 1;
		else
			index++;
	}

	if(found == 1) result = members_list.data[index];

	return &result;
}

int *
new_subscription_1_svc(subscription_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
total_subscriptions_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

subscription_t *
show_subscription_1_svc(int *argp, struct svc_req *rqstp)
{
	static subscription_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
update_subscription_1_svc(subscription_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
set_member_subscription_1_svc(set_member_subscription_params *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
new_collection_1_svc(collection_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
total_collections_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

collection_t *
show_collection_1_svc(int *argp, struct svc_req *rqstp)
{
	static collection_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
set_clothing_collecton_1_svc(set_clothing_collection_params *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
new_clothing_1_svc(cloth_t *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
total_clothings_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

cloth_t *
show_clothing_1_svc(int *argp, struct svc_req *rqstp)
{
	static cloth_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rent_clothing_1_svc(int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
total_rents_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

rental_t *
show_rental_1_svc(int *argp, struct svc_req *rqstp)
{
	static rental_t  result;

	/*
	 * insert server code here
	 */

	return &result;
}
